#!/bin/bash
# Aliases that don't belong anywhere else

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -lF'
alias clip='xclip -sel clip'

git config --global alias.ll 'log --graph --format="%C(yellow)%h%C(red)%d%C(reset) - %C(bold green)(%ar)%C(reset) %s %C(blue)<%an>%C(reset)"'
git config --global alias.subreset "!f() { \
        if [ \"$1\" = \"--hard\" ]; then \
            git submodule foreach --recursive 'git reset --hard && git clean -fdx'; \
        fi; \
        git submodule sync --recursive && \
        git submodule update --init --recursive; \
    }; f"

alias docker_clean_all='docker kill -f $(docker ps -q); docker rm -f $(docker ps --filter=status=exited --filter=status=created -q); docker rmi -f $(docker images -a -q);'

if [[ ! -v $IS_SSH ]]; then
    alias vim='nvim'
    alias wi='vim ~/vimwiki/index.md'
fi

alias claude-personal='CLAUDE_CONFIG_DIR=$HOME/.claude-personal claude'
alias claude-work='CLAUDE_CONFIG_DIR=$HOME/.claude-work claude'
