#!/bin/bash

# ANSI color codes
RESET='\[\033[0m\]'
BOLD='\[\033[1m\]'
BLUE='\[\033[34m\]'
GREY='\[\033[38;5;244m\]'
RED='\[\033[31m\]'
YELLOW='\[\033[33m\]'

# Git branch
__git_branch() {
  local branch
  branch=$(git symbolic-ref --short -q HEAD 2>/dev/null)
  [ -n "$branch" ] && printf "$branch"
}

# Git status
__git_status() {
  git rev-parse --is-inside-work-tree &>/dev/null || return

  local status=""
  if ! git symbolic-ref -q HEAD > /dev/null; then
    status+=" 🔀"
  elif [ -n "$(git status --porcelain 2>/dev/null)" ]; then
    status+=" ✗"
  fi

  printf "$status"
}

# Show SSH host
__host_prefix() {
  if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    printf "$USER@$(hostname):"
  fi
}

__venv_prefix() {
  if [[ -n "$VIRTUAL_ENV" ]]; then
    printf "($(basename "$VIRTUAL_ENV")) "
  fi
}

# Build prompt
__prompt() {
  local host="$(__host_prefix)"
  local venv="$(__venv_prefix)"
  local path=$(dirs +0)

  local branch="$(__git_branch)"
  local status="$(__git_status)"

  # Combine lengths
  local host_len=${#host}
  local path_len=${#path}
  local branch_len=${#branch}
  local status_len=${#status}
  local total_len=$((host_len + path_len + branch_len + status_len))

  local limit=40
  local newline=""
  local path_prefix=""
  local git_prefix=""
  local second_line_prefix=""

  if [ -n "$branch" ]; then
    git_prefix=" "
  fi

  if (( total_len > limit )); then
    newline="\n"
    path_prefix="→ "
  fi

  if [ -n "$venv" ]; then
      path_prefix=$venv
  fi

  if (( total_len > limit )); then
    len=${#path_prefix}
    second_line_prefix=$(printf '%*s' "$len" '')
  fi

  printf "${path_prefix}${host}${BLUE}${BOLD}${path}${RESET}${newline}"\
"${YELLOW}${second_line_prefix}${git_prefix}${branch}${RESET}"\
"${RED}$(echo "$status" | grep ✗)${RESET}"\
"${YELLOW}$(echo "$status" | grep 🔀)${RESET}"\
"${GREY} >>> ${RESET}"
}

# Set prompt
PROMPT_COMMAND='PS1="$(__prompt)"'
